services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb

  api:
    image: node:20-slim
    container_name: fastify_api
    working_dir: /bnj-text-analyzer
    env_file:
      - ./apps/api/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - .:/bnj-text-analyzer
      - /bnj-text-analyzer/node_modules
    environment:
      - PNPM_HOME=/root/.local/share/pnpm
      - PATH=$PATH:/root/.local/share/pnpm
    command: >
      sh -c "corepack enable && 
             pnpm config set store-dir /root/.pnpm-store && 
             pnpm install --force && 
             pnpm --filter @workspace/api dev"

  web:
    image: node:20-slim
    container_name: react_web
    working_dir: /bnj-text-analyzer
    ports:
      - "5173:5173"
    depends_on:
      - mongodb
    volumes:
      - .:/bnj-text-analyzer
      - /bnj-text-analyzer/node_modules
    environment:
      - PNPM_HOME=/root/.local/share/pnpm
      - PATH=$PATH:/root/.local/share/pnpm
    command: >
      sh -c "corepack enable && 
             pnpm config set store-dir /root/.pnpm-store && 
             pnpm install --force && 
             pnpm --filter @workspace/web dev"
volumes:
  mongodb_data: