services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27018/?authSource=admin
    depends_on:
      - mongodb

  api:
    image: node:20-slim
    container_name: fastify_api
    working_dir: /bnj-text-analyzer
    volumes:
      - .:/bnj-text-analyzer
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27018/analysis_db?authSource=admin
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    command: >
      sh -c "npm install -g pnpm && pnpm install --force && pnpm --filter @workspace/api dev"

volumes:
  mongodb_data: